apiVersion: v1
kind: Service
metadata:
  name: edge-mariadb-frontend-service
spec:
  type: NodePort
  selector:
    app: edge-mariadb-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30501
